export const Products  =  [
  {
    id: 1,
    image: './products/images/image1.jpg',
    desc: 'Reusable Capsules',
    price:'10',
    value: 0,
  },
  {
    id: 2,
    image: './products/images/image2.jpg',
    desc: 'Excelsa',
    price:'20',
    value: 0,
  },  {
    id: 3,
    image: './products/images/image3.jpg',
    desc: 'Mix and Match Set of 6',
    price:'95',
    value: 0,
  },  {
    id: 4,
    image: './products/images/image4.jpg',
    desc: 'Coffee Bean Surprise',
    price:'20',
    value: 3,
  },  {
    id: 5,
    image: './products/images/image5.jpg',
    desc: 'Liberica',
    price:'20',
    value: 0,
  },  {
    id: 6,
    image: './products/images/image6.jpg',
    desc: 'Coffee Pods',
    price:'45',
    value: 0,
  },  {
    id: 7,
    image: './products/images/image7.jpg',
    desc: 'Ceramic Coffee Mug Set',
    price:'30',
    value: 0,
  },  {
    id: 8,
    image: './products/images/image8.jpg',
    desc: 'Arabica',
    price:'20',
    value: 0,
  }, 
   {
    id: 9,
    image: './products/images/image9.jpg',
    desc: 'Robusta',
    price:'20',
    value: 0,
  },  {
    id: 10,
    image: './products/images/image10.jpg',
    desc: 'Trio Pack',
    price:'50',
    value: 0,
  },
]